### DISCUSSION TITLE
Error: reconnect error

### DISCUSSION THREAD

**Discussion by hugorn** [aldinokemal/go-whatsapp-web-multidevice#256] [General]
I installed the service v5.2.0 on a VPS and it is giving this message when clicking on the login button, on my machine using localhost:3000 I had no problems
http://xxx.xxx.xxx.xxx:3000/app/login 401 (Unauthorized)
![image](https://github.com/user-attachments/assets/182ddf88-fa0e-4cee-9158-b2ed46be565f)

**Comment by hugorn** [comment]
commenting out the authentication part also results in the same error

```
services:
  whatsapp:
    image: aldinokemal2104/go-whatsapp-web-multidevice
    container_name: whatsapp
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - whatsapp:/app/storages
    environment:
#      - APP_BASIC_AUTH=admin:admin
      - APP_PORT=3000
      - APP_DEBUG=true
      - APP_OS=Chrome
      - APP_ACCOUNT_VALIDATION=false

volumes:
  whatsapp:
```
